apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seneca-mesh-base
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: seneca-mesh-base
    spec:
      containers:
      - name: seneca-mesh-base
        image: 711655675495.dkr.ecr.eu-central-1.amazonaws.com/seneca-consul-base
        ports:
        - containerPort: 39999
          protocol: UDP
        - containerPort: 39999
          protocol: TCP
